spring:
  mustache:
    servlet:
      expose-session-attributes: 'true'
      cache: 'false'
    suffix: .html
  mvc:
    hidden-method:
      filter:
        enabled: 'true'
    path-match:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/spring_cafe?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
  sql:
    init:
      mode: always
server:
  servlet:
    encoding:
      force-response: 'true'
